/** Every user-facing string in the staff admin area. Later steps append their page copy here. */
export const adminCopy = {
  navLabel: 'Staff pages',
  nav: {
    queue: 'Queue',
    followUp: 'Follow-up',
    calls: 'Calls',
    reports: 'Reports',
    exports: 'Exports',
    audit: 'Audit',
    settings: 'Settings',
    knowledge: 'Knowledge',
    agents: 'Agents',
    forms: 'Forms',
    versions: 'Versions',
    account: 'Account',
  },
  pages: {
    queue: 'Review queue',
    'follow-up': 'Follow-up',
    calls: 'Calls',
    'call-detail': 'Call',
    reports: 'Reports',
    exports: 'Exports',
    audit: 'Audit log',
    settings: 'Settings',
    knowledge: 'Knowledge base',
    agents: 'Agents',
    'agent-editor': 'Agent',
    forms: 'Forms',
    'form-builder': 'Form',
    versions: 'Versions',
    'version-detail': 'Version',
  },
  placeholderBody: 'This page is being built.',
  logout: 'Sign out',
  loggingOut: 'Signing out…',
  logoutError: 'Could not sign out. Try again.',
  authLoading: 'Checking your session',
  authError: 'Could not check your session.',
  retry: 'Retry',
  loadingArea: 'Loading staff area',
  forbidden: {
    title: "You don't have access to this page",
    body: 'Only admins can open it. Ask an admin if you need it.',
    link: 'Go to the queue',
  },
  login: {
    title: 'Staff sign-in',
    heading: 'Staff sign-in',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    invalid: 'Email or password is incorrect.',
    tooMany: 'Too many attempts, try again shortly.',
    failed: 'Could not sign in. Check your connection and try again.',
  },
  account: {
    title: 'Account',
    heading: 'Your account',
    signedInAs: 'Signed in as',
    forced: 'Choose a new password to continue',
    current: 'Current password',
    next: 'New password',
    nextHint: 'At least 12 characters.',
    confirm: 'Confirm new password',
    submit: 'Change password',
    submitting: 'Changing…',
    currentRequired: 'Enter your current password.',
    tooShort: 'Use at least 12 characters.',
    mismatch: 'The passwords do not match.',
    wrongCurrent: 'Your current password is incorrect.',
    tooMany: 'Too many attempts, try again shortly.',
    failed: 'Could not change the password. Try again.',
    success: 'Password changed',
  },
  loading: 'Loading',
  openCall: 'Open call',
  none: 'None',
  dash: '—',
  apply: 'Apply',
  clear: 'Clear',
  any: 'Any',
  previous: 'Previous page',
  next: 'Next page',
  cols: {
    submitted: 'Submitted',
    afterHours: 'After hours',
    language: 'Language',
    category: 'Category',
    route: 'Route',
    flags: 'Open flags',
    call: 'Call',
    started: 'Started',
    ended: 'Ended',
    status: 'Status',
    outcome: 'Outcome',
    formStatus: 'Form status',
    tester: 'Tester',
    agentVersion: 'Agent version',
    voiceMode: 'Voice mode',
    reason: 'Reason',
    caller: 'Caller',
    action: 'Action',
    decided: 'Approved',
    relationship: 'Caller relationship',
    time: 'Time',
    actor: 'Actor',
    staffEmail: 'Staff email',
    target: 'Target',
    count: 'Count',
    period: 'Period start',
    turns: 'Turns',
    actions: 'Actions',
    p50: 'p50 (ms)',
    p90: 'p90 (ms)',
    kind: 'Kind',
    story: 'Story',
    mode: 'Mode',
    repeat: 'Repeat',
    passed: 'Result',
    stop: 'Stopped because',
    turnsBeforeRoute: 'Turns before routing',
    duration: 'Duration (s)',
    spend: 'Spend',
    findings: 'Findings (table · key · count)',
    file: 'File',
  },
  queue: {
    caption: 'Forms waiting for approval, after-hours first, then oldest first',
    empty: 'No forms waiting.',
    emptyBody: 'New ones appear after a caller confirms.',
    error: 'Could not load the queue.',
    refresh: 'Refresh',
    afterHours: 'After hours',
    stale: (time: string) => `Showing the queue from ${time} — couldn't refresh.`,
  },
  followUp: {
    caption: 'Calls waiting for a person, oldest first',
    empty: 'Nobody is waiting for a person.',
    error: 'Could not load the follow-up list.',
    acknowledge: 'Acknowledge',
    acknowledging: 'Acknowledging…',
    done: 'Marked as handled',
    conflict: 'Someone already handled this',
    failed: 'Could not mark it as handled. Try again.',
    form: 'Form',
  },
  calls: {
    caption: 'Calls, newest first',
    filters: 'Filter calls',
    dateFrom: 'From date',
    dateTo: 'To date',
    hasFlags: 'Open flags',
    onlyFlagged: 'Only with open flags',
    empty: 'No calls yet',
    emptyBody: 'Calls appear here once someone phones the line.',
    filteredEmpty: 'No calls match these filters',
    filteredEmptyBody: 'Change or clear the filters.',
    error: 'Could not load calls.',
    live: 'Live',
    ended: 'Ended',
  },
  reports: {
    form: 'Report period',
    period: 'Group by',
    day: 'Day',
    week: 'Week',
    unmet: 'Unmet demand',
    outcomes: 'Outcomes by category',
    routing: 'Routing mix',
    latency: 'Agent turn latency',
    delegation: 'Delegation time',
    total: (n: number) => `${n} ${n === 1 ? 'call' : 'calls'} in this period`,
    empty: 'Not enough calls in this period',
    emptyBody: 'Pick a wider period or another agent version.',
    error: 'Could not load reports.',
    gates: 'Release-gate and story-harness results',
    gatesEmpty: 'No gate results yet — they appear once the release-gate command publishes them',
    gatesCaption: 'Release gate and story harness runs, gate first, then harness, then live',
    kinds: { gate: 'Release gate', harness: 'Story harness', live: 'Live check' },
    passed: '✓ Passed',
    failed: '✗ Failed',
    unapproved: 'Unapproved content',
    unapprovedCaption: 'Placeholder content not yet approved by the clinic',
    unapprovedEmpty: 'All content is approved by the clinic',
  },
  exports: {
    caption: 'Approved forms not yet exported',
    run: 'Export',
    running: 'Exporting…',
    result: (n: number) => `Exported ${n} ${n === 1 ? 'form' : 'forms'}`,
    failed: 'Could not export. Try again.',
    empty: 'Nothing approved since the last export',
    error: 'Could not load forms ready to export.',
  },
  voiceModes: {
    'gpt-live': 'GPT-Live + Luna',
    realtime: 'Realtime (no Luna)',
  },
  settings: {
    voiceMode: 'Voice mode for new calls',
    voiceModeHint: 'Applies to calls that start after you save. Calls in progress keep their mode.',
    options: {
      'gpt-live': {
        label: 'GPT-Live + Luna',
        hint: 'GPT-Live speaks; Luna calls the functions. Calls are recorded.',
      },
      realtime: {
        label: 'Realtime (no Luna)',
        hint: 'One Realtime model speaks and calls the functions itself. Calls are not recorded.',
      },
    },
    current: 'Current',
    defaultNote: 'Nothing saved yet: the server default is in use.',
    lastChanged: (when: string) => `Last changed ${when}`,
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved. New calls use this mode.',
    saveError: 'Could not save. The previous mode is still in use. Try again.',
    error: 'Could not load the voice mode.',
    loading: 'Loading the voice mode',
  },
  audit: {
    caption: 'Audit entries, newest first',
    filter: 'Action',
    all: 'All actions',
    empty: 'No audit entries yet',
    filteredEmpty: 'No entries for this action',
    error: 'Could not load the audit log.',
  },
  detail: {
    summary: 'Summary',
    notFound: "This call doesn't exist",
    backToCalls: 'Back to calls',
    error: 'Could not load this call.',
    failed: 'Could not save. Try again.',
    conflict: 'Someone else changed this form — showing the latest',
    live: 'In progress — read-only',
    inProgress: 'In progress',
    jump: 'Jump to transcript',
    statedName: 'Stated name',
    statedReason: 'Stated reason',
    recording: 'Recording',
    audioLabel: 'Call recording',
    recordingUnavailable: (reason: string) => `Recording unavailable — ${reason}`,
    noRecordingRealtime: 'No recording (Realtime mode)',
    noReason: 'no audio was saved',
    liveReason: 'the call is still in progress',
    transcript: 'Transcript',
    sessions: 'Sessions',
    session: (seq: number) => `Session ${seq}`,
    voice: 'voice',
    endReason: 'ended by',
    noSessions: 'No sessions recorded.',
    timeline: 'Timeline',
    emptyTimeline: 'Nothing was said on this call.',
    caller: 'Caller',
    agent: 'Agent',
    action: 'Action',
    flag: 'Flag',
    field: 'field',
    latency: (ms: number) => `latency ${ms} ms`,
    delegation: (ms: number) => `delegation ${ms} ms`,
    acknowledge: 'Acknowledge',
    acknowledging: 'Acknowledging…',
    acknowledgeFlag: (kind: string) => `Acknowledge ${kind} flag`,
    flagAcked: 'Flag acknowledged',
    form: 'Form',
    noForm: (outcome: string) => `No form — this call ended as ${outcome}`,
    noFormYet: 'No form — this call has no outcome yet',
    afterHoursQueued: 'Queued after hours',
    submitted: 'Submitted',
    decided: 'Decided',
    exported: 'Exported',
    rejectReasonShown: 'Reject reason',
    fieldLabels: {
      caller_relationship: 'Caller relationship',
      insurance_carrier_verbatim: 'Insurance carrier',
      callback_number: 'Callback number',
      callback_consent: 'Callback consent',
      documents_held: 'Documents held',
    } as Record<string, string>,
    listHint: 'Separate items with commas.',
    save: 'Save',
    saveField: (field: string) => `Save ${field}`,
    saved: (field: string) => `Saved ${field}`,
    approve: 'Approve',
    approving: 'Approving…',
    approved: 'Form approved',
    approveHint: 'Acknowledge the flags first',
    reject: 'Reject',
    rejectReason: 'Reason for rejecting',
    reasonRequired: 'Enter a reason for rejecting.',
    reasonTooLong: 'Use 500 characters or fewer.',
    confirmReject: 'Confirm reject',
    rejecting: 'Rejecting…',
    rejected: 'Form rejected',
    cancel: 'Cancel',
    history: 'Field history',
    historyEmpty: 'No changes yet.',
  },
  config: {
    loading: 'Loading the configuration',
    error: 'Could not load the configuration.',
    live: 'Live version',
    entryAgent: 'Answers new calls',
    noChanges: 'No changes in the draft.',
    changed: (n: number) => `${n} section${n === 1 ? '' : 's'} changed in the draft.`,
    problems: (n: number) => `${n} problem${n === 1 ? '' : 's'} to fix before publishing.`,
    problemsTitle: 'Fix these before publishing',
    readOnly: 'You can read the configuration. Only admins can change it.',
    publish: 'Publish…',
    publishing: 'Publishing…',
    publishTitle: 'Publish the draft?',
    publishBody:
      'New calls start on the new version right away. Calls in progress keep the version they started on.',
    publishNote: 'Note (optional)',
    publishConfirm: 'Publish',
    published: (label: string) => `${label} is live for new calls. Calls in progress keep their version.`,
    publishFailed: 'Could not publish. Fix the problems listed and try again.',
    stale: 'Someone published since this draft was started. Discard the draft to start from the live version.',
    discard: 'Discard draft…',
    discardTitle: 'Discard the draft?',
    discardBody: 'Every unpublished change is replaced by the live version.',
    discardConfirm: 'Discard',
    drift: 'The repo defaults differ from the live version.',
    loadDefaults: 'Load repo defaults…',
    loadDefaultsTitle: 'Load the repo defaults?',
    loadDefaultsBody:
      'The draft is replaced by the defaults in the code repository. Review the changes, then publish.',
    loadDefaultsConfirm: 'Load defaults',
    fallback: 'The newest version could not be loaded with this code, so an older one is running.',
    reloadPending: 'Published, but this server has not loaded it yet. It retries on the next call.',
    viewChanges: 'Show the draft changes',
    hideChanges: 'Hide the draft changes',
    saved: 'Saved to the draft.',
    saveFailed: 'Could not save. Check the values and try again.',
    status: 'Approval status',
    statusOptions: [
      { value: 'UNAPPROVED', label: 'Unapproved (placeholder)' },
      { value: 'APPROVED', label: 'Approved by the clinic' },
    ],
    locked: 'Locked: set in code, cannot be removed here.',
    lockedBadge: 'Locked',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    remove: 'Remove',
    save: 'Save to draft',
    saving: 'Saving…',
    cancel: 'Cancel',
    back: 'Back',
    empty: 'Nothing here yet.',
    noMatch: 'Nothing matches this search.',
    sections: {
      routing: 'Routing',
      services: 'Services',
      referrals: 'Referrals',
      hours: 'Hours & closures',
      wording: 'Wording',
      crisis: 'Crisis',
      never_spoken: 'Never spoken',
      clinic: 'Clinical terms',
    } as Record<string, string>,
    sectionHints: {
      routing:
        'Where callers can be sent. A row handled by an agent passes the caller to that agent; any other row is a department: the caller hears its line and the request is recorded.',
      services: 'Approved service details the agents can look up.',
      referrals: 'Needs the clinic does not meet, with the approved referral line.',
      hours: 'Opening hours and closure days (after hours, requests are still taken).',
      wording: 'Fixed lines the agents say (greeting with the recording notice, human-needed, corrections).',
      crisis:
        'Crisis phrases stop the call at once. The built-in phrases, numbers and instruction are locked; you can add phrases.',
      never_spoken: 'Names and terms an agent must never say. Built-in entries are locked; you can add more.',
      clinic:
        'Clinical requests are never taken by a form: these terms stop the form for staff. Built-in terms are locked.',
    } as Record<string, string>,
  },
  agents: {
    newAgent: 'New agent',
    entryLabel: 'Agent that answers new calls',
    entrySave: 'Save',
    name: 'Name',
    takesCallsFor: 'Takes calls for',
    tools: 'Tools',
    voice: 'Voice',
    status: 'Status',
    active: 'Active',
    archived: 'Archived',
    entry: 'Answers new calls',
    empty: 'No agents yet.',
    error: 'Could not load the agents.',
    notFound: 'There is no agent with this name in the draft.',
    nameField: 'Name (lowercase letters, digits, _)',
    nameHint: 'Used in the routing table and reports. Cannot change later.',
    title: 'Title',
    titleHint: 'How the agent is named, e.g. "Residential Programs".',
    persona: 'Persona',
    personaHint: 'Who this agent is, its tone, and what it helps with, in plain language.',
    knowledge: 'What it knows',
    knowledgeHint: 'Short facts or FAQ answers. Shared knowledge (services, referrals, hours) is always included.',
    topic: 'Topic',
    text: 'Answer',
    addItem: 'Add a fact',
    removeItem: 'Remove fact',
    toolsHint: 'Each tool is code; pick what this agent may do. Safety checks always apply.',
    formGroup: 'Fill a form: save details, confirm the callback number, submit',
    formPick: 'Form',
    noForm: 'Choose a form',
    redirectTargets: 'May redirect to',
    redirectHint: 'Departments (the caller hears the line) and agents (the caller is passed on live).',
    agentTarget: (name: string) => `agent: ${name}`,
    departmentTarget: 'department',
    handoff: 'When another agent passes a caller here',
    bridgeSay: 'Line the previous agent says (English)',
    bridgeSayEs: 'Line the previous agent says (Spanish)',
    greeting: 'How this agent takes over',
    greetingHint: 'A plain instruction, e.g. "Greet the caller and ask your first question."',
    archivedLabel: 'Archived (kept in history; takes no calls)',
    compiled: 'Generated instructions (read-only)',
    compiledHint: 'Written by code from the settings above. Shown for checking only.',
    compiledError: 'The draft has problems, so no instructions can be generated yet.',
    gptLive: 'GPT-Live voice prompt',
    luna: 'Tool rules (Luna)',
    realtime: 'Realtime prompt',
    problems: 'Problems with this agent',
    sameEditor: 'Switchboard and clinic are agents like any other: every setting here can change.',
  },
  forms: {
    newForm: 'New form',
    empty: 'No forms yet.',
    error: 'Could not load the forms.',
    notFound: 'There is no form with this name in the draft.',
    usedBy: 'Used by',
    fieldsCount: 'Fields',
    name: 'Name (lowercase letters, digits, _)',
    title: 'Title',
    fields: 'Fields',
    fieldsHint: 'Asked in this order. The callback number and permission are always added by the system.',
    addField: 'Add a field',
    key: 'Key (lowercase letters, digits, _)',
    label: 'Label',
    type: 'Type',
    required: 'Required',
    help: 'What to ask (one line for the agent)',
    readback: 'Read-back label',
    values: 'Choices',
    stopValues: 'Stop choices: picking one hands the call to staff',
    maxLength: 'Max length',
    maxItems: 'Max items',
    minimum: 'Minimum',
    maximum: 'Maximum',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove field',
    neverCollect: 'Never collected (built-in, always refused)',
    problems: 'Problems with this form',
    archivedLabel: 'Archived (kept in history; no agent can use it)',
  },
  versions: {
    empty: 'No versions yet.',
    error: 'Could not load the versions.',
    seq: 'Version',
    label: 'Label',
    source: 'Source',
    by: 'By',
    when: 'When',
    note: 'Note',
    live: 'Live',
    sources: { seed: 'Repo defaults', admin: 'Published', rollback: 'Rollback' } as Record<string, string>,
    diffTitle: 'Changes from the version before',
    noDiff: 'No differences.',
    rollback: 'Roll back to this…',
    rollbackTitle: 'Roll back to this version?',
    rollbackBody: 'A copy of this version is published as a new version. Nothing is deleted.',
    rollbackConfirm: 'Roll back',
    rolledBack: (label: string) => `${label} is live for new calls.`,
    rollbackFailed: 'This version does not pass today’s checks and cannot be restored.',
    notFound: 'There is no such version.',
  },
} as const

export type AdminPageKey = keyof typeof adminCopy.pages

type Tone = 'ok' | 'error' | 'warning'

/** "human_needed" → "Human needed"; null → dash. */
export function label(value: string | null | undefined): string {
  if (!value) return adminCopy.dash
  const text = value.replace(/_/g, ' ')
  return text.charAt(0).toUpperCase() + text.slice(1)
}

export function orDash(value: string | null | undefined): string {
  return value ? value : adminCopy.dash
}

/** Local date and time for a server timestamp. */
export function formatTime(iso: string | null | undefined): string {
  if (!iso) return adminCopy.dash
  return new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })
}

/** Local HH:MM for an epoch-ms value. */
export function formatClock(ms: number): string {
  return new Date(ms).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
}

/** YYYY-MM-DD in local time. */
export function localDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

export function outcomeTone(outcome: string | null | undefined): Tone {
  if (outcome === 'crisis' || outcome === 'error') return 'error'
  if (outcome === 'routed' || outcome === 'referred' || outcome === 'clinic_form') return 'ok'
  return 'warning'
}

export function formStatusTone(status: string | null | undefined): Tone {
  if (status === 'rejected') return 'error'
  if (status === 'incomplete' || status === 'flagged') return 'warning'
  return 'ok'
}

/** Local time of day with seconds, for timeline entries. */
export function formatTimeOfDay(iso: string): string {
  return new Date(iso).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', second: '2-digit' })
}

export function yesNo(value: boolean | null | undefined): string {
  if (value === null || value === undefined) return adminCopy.dash
  return value ? 'Yes' : 'No'
}
