/** Every user-facing string in the staff admin area. Later steps append their page copy here. */
export const adminCopy = {
  navLabel: 'Staff pages',
  menu: 'Menu',
  currentSection: '(you are here)',
  navGroups: { daily: 'Daily work', setup: 'Setup', more: 'More' },
  /** Shared words for every admin edit form: required/optional markers, missing fields, problems. */
  fields: {
    required: 'Required',
    optional: '(optional)',
    fillIn: (labels: string) => `Fill in before saving: ${labels}`,
    advanced: 'Advanced',
    keyHint: 'Filled in from the name. Change it only if you need to; it cannot change after saving.',
    note: 'Note (where this info came from)',
    noteHint: 'For staff: for example the clinic website or who told you.',
    problemsTitle: 'Please fix these and save again:',
    wholeSection: 'This section',
    atLeastOneField: 'at least one field',
    fieldN: (n: number) => `Field ${n}`,
    item: (n: number) => `Fact ${n}`,
    row: (n: number, name: string) => (name ? `Row ${n} (${name})` : `Row ${n}`),
    words: {
      missing: 'is missing',
      string_too_short: 'cannot be empty',
      too_short: 'needs at least one entry',
      string_too_long: 'is too long',
      too_long: 'has too many entries',
      string_type: 'must be text',
      list_type: 'must be a list',
      int_parsing: 'must be a whole number',
      int_type: 'must be a whole number',
      bool_type: 'must be yes or no',
      date_from_datetime_parsing: 'must be a date',
      date_parsing: 'must be a date',
      extra_forbidden: 'is not allowed here',
      literal_error: 'is not one of the allowed choices',
      string_pattern_mismatch: 'has characters that are not allowed (use lowercase letters, numbers and _)',
      greater_than: 'is too small',
      greater_than_equal: 'is too small',
      less_than_equal: 'is too large',
      value_error: 'is not valid',
    } as Record<string, string>,
  },
  nav: {
    home: 'Home',
    queue: 'Approval queue',
    followUp: 'Follow-up',
    calls: 'Calls',
    reports: 'Reports',
    exports: 'Exports',
    audit: 'Audit log',
    settings: 'Voice settings',
    knowledge: 'Knowledge',
    departments: 'Departments',
    agents: 'Agents',
    forms: 'Forms',
    versions: 'History',
    account: 'Account',
  },
  pages: {
    home: 'Home',
    queue: 'Approval queue',
    'follow-up': 'Follow-up',
    calls: 'Calls',
    'call-detail': 'Call',
    reports: 'Reports',
    exports: 'Exports',
    audit: 'Audit log',
    settings: 'Voice settings',
    knowledge: 'Knowledge',
    departments: 'Departments',
    agents: 'Agents',
    'agent-editor': 'Agent',
    forms: 'Forms',
    'form-builder': 'Form',
    versions: 'History',
    'version-detail': 'Saved setup',
  },
  /** One plain line under every page title: what the page is for. */
  help: {
    home: 'What is happening today, and what to set up next.',
    queue: 'Forms callers filled in. Check each one, then approve or reject it.',
    'follow-up': 'Callers who need a person to call them back.',
    calls: 'Every call to the line. Open one to read it or play the recording.',
    'call-detail': 'Everything said and done on this call.',
    reports: 'How the line is doing: what callers needed and where they were sent.',
    exports: 'Send approved forms on to the clinic.',
    audit: 'Who did what in this admin area.',
    settings: 'How the assistant speaks on new calls.',
    knowledge: 'What the assistant knows: opening hours, services, referrals and its standard sentences.',
    departments: 'The departments callers can be sent to, and what the caller hears for each.',
    agents: 'The assistants that talk to callers, and which one answers calls first.',
    'agent-editor': 'Who this assistant is, what it knows and what it may do.',
    forms: 'Optional: forms an assistant fills in with the caller, for staff to approve.',
    'form-builder': 'The questions this form asks, in order.',
    versions: 'Every time changes went live. You can go back to an earlier setup.',
    'version-detail': 'What changed when this setup went live.',
    account: 'Your sign-in details.',
  } as Record<string, string>,
  placeholderBody: 'This page is being built.',
  logout: 'Sign out',
  loggingOut: 'Signing out…',
  logoutError: 'Could not sign out. Try again.',
  authLoading: 'Checking your session',
  authError: 'Could not check your session.',
  retry: 'Retry',
  loadingArea: 'Loading staff area',
  forbidden: {
    title: "You don't have access to this page",
    body: 'Only admins can open it. Ask an admin if you need it.',
    link: 'Go to Home',
  },
  login: {
    title: 'Staff sign-in',
    heading: 'Staff sign-in',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    invalid: 'Email or password is incorrect.',
    tooMany: 'Too many attempts, try again shortly.',
    failed: 'Could not sign in. Check your connection and try again.',
  },
  account: {
    title: 'Account',
    heading: 'Your account',
    signedInAs: 'Signed in as',
    forced: 'Choose a new password to continue',
    current: 'Current password',
    next: 'New password',
    nextHint: 'At least 12 characters.',
    confirm: 'Confirm new password',
    submit: 'Change password',
    submitting: 'Changing…',
    currentRequired: 'Enter your current password.',
    tooShort: 'Use at least 12 characters.',
    mismatch: 'The passwords do not match.',
    wrongCurrent: 'Your current password is incorrect.',
    tooMany: 'Too many attempts, try again shortly.',
    failed: 'Could not change the password. Try again.',
    success: 'Password changed',
  },
  loading: 'Loading',
  openCall: 'Open call',
  none: 'None',
  dash: '—',
  apply: 'Apply',
  clear: 'Clear',
  any: 'Any',
  previous: 'Previous page',
  next: 'Next page',
  cols: {
    submitted: 'Submitted',
    afterHours: 'After hours',
    language: 'Language',
    category: 'Category',
    route: 'Sent to',
    flags: 'Open flags',
    call: 'Call',
    started: 'Started',
    ended: 'Ended',
    status: 'Status',
    outcome: 'Outcome',
    formStatus: 'Form status',
    tester: 'Tester',
    agentVersion: 'Setup',
    voiceMode: 'Voice',
    reason: 'Reason',
    caller: 'Caller',
    action: 'Action',
    decided: 'Approved',
    relationship: 'Caller relationship',
    time: 'Time',
    actor: 'Actor',
    staffEmail: 'Staff email',
    target: 'Target',
    count: 'Count',
    period: 'Period start',
    turns: 'Turns',
    actions: 'Actions',
    p50: 'Typical (ms)',
    p90: 'Slowest 10% (ms)',
    kind: 'Kind',
    story: 'Story',
    mode: 'Mode',
    repeat: 'Repeat',
    passed: 'Result',
    stop: 'Stopped because',
    turnsBeforeRoute: 'Turns before sending on',
    duration: 'Duration (s)',
    spend: 'Spend',
    findings: 'Findings (table · key · count)',
    file: 'File',
  },
  queue: {
    caption: 'Forms waiting for approval, after-hours first, then oldest first',
    empty: 'No forms waiting.',
    emptyBody: 'New ones appear after a caller confirms.',
    error: 'Could not load the queue.',
    refresh: 'Refresh',
    afterHours: 'After hours',
    stale: (time: string) => `Showing the queue from ${time} — couldn't refresh.`,
  },
  followUp: {
    caption: 'Calls waiting for a person, oldest first',
    empty: 'Nobody is waiting for a person.',
    error: 'Could not load the follow-up list.',
    acknowledge: 'Acknowledge',
    acknowledging: 'Acknowledging…',
    done: 'Marked as handled',
    conflict: 'Someone already handled this',
    failed: 'Could not mark it as handled. Try again.',
    form: 'Form',
  },
  calls: {
    caption: 'Calls, newest first',
    filters: 'Filter calls',
    dateFrom: 'From date',
    dateTo: 'To date',
    hasFlags: 'Open flags',
    onlyFlagged: 'Only with open flags',
    empty: 'No calls yet',
    emptyBody: 'Calls appear here once someone phones the line.',
    filteredEmpty: 'No calls match these filters',
    filteredEmptyBody: 'Change or clear the filters.',
    error: 'Could not load calls.',
    live: 'Live',
    ended: 'Ended',
  },
  reports: {
    form: 'Report period',
    period: 'Group by',
    day: 'Day',
    week: 'Week',
    unmet: 'Unmet demand',
    outcomes: 'Outcomes by category',
    routing: 'Where callers were sent',
    latency: 'How fast the assistant answered',
    delegation: 'Time spent looking things up',
    total: (n: number) => `${n} ${n === 1 ? 'call' : 'calls'} in this period`,
    empty: 'Not enough calls in this period',
    emptyBody: 'Pick a wider period or another setup.',
    error: 'Could not load reports.',
    gates: 'Automatic checks',
    gatesEmpty: 'No automatic checks yet. They appear after the developer runs them.',
    gatesCaption: 'Automatic check runs, newest group first',
    kinds: { gate: 'Safety check', harness: 'Practice calls', live: 'Live check' },
    passed: '✓ Passed',
    failed: '✗ Failed',
    unapproved: 'Unapproved content',
    unapprovedCaption: 'Placeholder content not yet approved by the clinic',
    unapprovedEmpty: 'All content is approved by the clinic',
  },
  exports: {
    caption: 'Approved forms not yet exported',
    run: 'Export',
    running: 'Exporting…',
    result: (n: number) => `Exported ${n} ${n === 1 ? 'form' : 'forms'}`,
    failed: 'Could not export. Try again.',
    empty: 'Nothing approved since the last export',
    error: 'Could not load forms ready to export.',
  },
  voiceModes: {
    'gpt-live': 'Standard (recorded)',
    realtime: 'Single voice (not recorded)',
  },
  settings: {
    voiceMode: 'Voice for new calls',
    voiceModeHint: 'Applies to calls that start after you save. Calls in progress keep their voice.',
    options: {
      'gpt-live': {
        label: 'Standard (recorded)',
        hint: 'One voice talks while a helper looks things up and fills forms. Calls are recorded.',
      },
      realtime: {
        label: 'Single voice (not recorded)',
        hint: 'One voice talks and does everything itself. Calls are not recorded.',
      },
    },
    current: 'Current',
    defaultNote: 'Nothing saved yet: the server default is in use.',
    lastChanged: (when: string) => `Last changed ${when}`,
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved. New calls use this voice.',
    saveError: 'Could not save. The previous voice is still in use. Try again.',
    error: 'Could not load the voice setting.',
    loading: 'Loading the voice setting',
  },
  audit: {
    caption: 'Audit entries, newest first',
    filter: 'Action',
    all: 'All actions',
    empty: 'No audit entries yet',
    filteredEmpty: 'No entries for this action',
    error: 'Could not load the audit log.',
  },
  detail: {
    summary: 'Summary',
    notFound: "This call doesn't exist",
    backToCalls: 'Back to calls',
    error: 'Could not load this call.',
    failed: 'Could not save. Try again.',
    conflict: 'Someone else changed this form — showing the latest',
    live: 'In progress — read-only',
    inProgress: 'In progress',
    jump: 'Jump to transcript',
    statedName: 'Stated name',
    statedReason: 'Stated reason',
    recording: 'Recording',
    audioLabel: 'Call recording',
    recordingUnavailable: (reason: string) => `Recording unavailable — ${reason}`,
    noRecordingRealtime: 'No recording (single voice)',
    noReason: 'no audio was saved',
    liveReason: 'the call is still in progress',
    transcript: 'Transcript',
    sessions: 'Sessions',
    session: (seq: number) => `Session ${seq}`,
    voice: 'voice',
    endReason: 'ended by',
    noSessions: 'No sessions recorded.',
    timeline: 'Timeline',
    emptyTimeline: 'Nothing was said on this call.',
    caller: 'Caller',
    agent: 'Agent',
    action: 'Action',
    flag: 'Flag',
    field: 'field',
    latency: (ms: number) => `latency ${ms} ms`,
    delegation: (ms: number) => `delegation ${ms} ms`,
    acknowledge: 'Acknowledge',
    acknowledging: 'Acknowledging…',
    acknowledgeFlag: (kind: string) => `Acknowledge ${kind} flag`,
    flagAcked: 'Flag acknowledged',
    form: 'Form',
    noForm: (outcome: string) => `No form — this call ended as ${outcome}`,
    noFormYet: 'No form — this call has no outcome yet',
    afterHoursQueued: 'Queued after hours',
    submitted: 'Submitted',
    decided: 'Decided',
    exported: 'Exported',
    rejectReasonShown: 'Reject reason',
    fieldLabels: {
      caller_relationship: 'Caller relationship',
      insurance_carrier_verbatim: 'Insurance carrier',
      callback_number: 'Callback number',
      callback_consent: 'Callback consent',
      documents_held: 'Documents held',
    } as Record<string, string>,
    listHint: 'Separate items with commas.',
    save: 'Save',
    saveField: (field: string) => `Save ${field}`,
    saved: (field: string) => `Saved ${field}`,
    approve: 'Approve',
    approving: 'Approving…',
    approved: 'Form approved',
    approveHint: 'Acknowledge the flags first',
    reject: 'Reject',
    rejectReason: 'Reason for rejecting',
    reasonRequired: 'Enter a reason for rejecting.',
    reasonTooLong: 'Use 500 characters or fewer.',
    confirmReject: 'Confirm reject',
    rejecting: 'Rejecting…',
    rejected: 'Form rejected',
    cancel: 'Cancel',
    history: 'Field history',
    historyEmpty: 'No changes yet.',
  },
  config: {
    loading: 'Loading the setup',
    error: 'Could not load the setup.',
    live: 'Live now',
    entryAgent: 'Answers calls',
    readOnly: 'You can look at the setup. Only admins can change it.',
    saved: 'Saved. Make your changes live when you are ready.',
    saveFailed: 'Could not save. Check the values and try again.',
    status: 'Approval status',
    statusOptions: [
      { value: 'UNAPPROVED', label: 'Not yet approved by the clinic' },
      { value: 'APPROVED', label: 'Approved by the clinic' },
    ],
    locked: 'Always on: built in for safety, cannot be removed here.',
    lockedBadge: 'Always on',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    remove: 'Remove',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    back: 'Back',
    empty: 'Nothing here yet.',
    noMatch: 'Nothing matches this search.',
    /** Knowledge page order: the setup order (basics first, safety additions last). */
    knowledgeOrder: ['hours', 'services', 'referrals', 'wording', 'crisis', 'never_spoken', 'clinic'] as const,
    sections: {
      routing: 'Departments',
      services: 'Services',
      referrals: 'Referrals',
      hours: 'Hours & closures',
      wording: 'Standard sentences',
      crisis: 'Crisis words',
      never_spoken: 'Never say',
      clinic: 'Medical topics',
    } as Record<string, string>,
    sectionHints: {
      routing:
        'Each department is a place callers can be sent. If an assistant handles it, the caller is passed to that assistant; otherwise the caller hears the line you write and the request is recorded for staff.',
      services: 'What the clinic offers, so the assistant can answer questions about it.',
      referrals: 'Things the clinic does not offer, with where to send the caller instead.',
      hours: 'When the clinic is open, and days it is closed. Outside these hours requests are still taken.',
      wording: 'Fixed sentences the assistant says, like the greeting with the recording notice.',
      crisis:
        'Words that mean a caller may be in danger: the call stops and the caller hears the crisis numbers. Built-in words are always on; you can add more.',
      never_spoken: 'Names and words the assistant must never say. Built-in ones are always on; you can add more.',
      clinic:
        'Medical topics the assistant never takes on a form: these send the caller to staff. Built-in ones are always on.',
    } as Record<string, string>,
  },
  changes: {
    pending: "You have changes that aren't live yet.",
    makeLive: 'Make changes live',
    makingLive: 'Making live…',
    discard: 'Discard',
    unsaved: 'Save or cancel your edits first.',
    fixFirst: (n: number) => `Fix ${n === 1 ? 'this' : `these ${n}`} before making changes live:`,
    stale: 'Someone else made changes live since you started. Discard your changes to start again from what is live now.',
    liveTitle: 'Make your changes live?',
    liveBody: 'New calls use your changes right away. Calls in progress keep what they started with.',
    liveNote: 'What did you change? (optional)',
    liveConfirm: 'Make live',
    madeLive: 'Your changes are live for new calls.',
    liveFailed: 'Could not make the changes live. Try again.',
    discardTitle: 'Discard your changes?',
    discardBody: 'Everything you changed since the last time is replaced by what is live now.',
    discardConfirm: 'Discard changes',
    discardFailed: 'Could not discard. Try again.',
    changedIn: 'Changed:',
    places: {
      entry_agent: 'Who answers calls',
      agents: 'Agents',
      forms: 'Forms',
    } as Record<string, string>,
    example: 'Load example setup',
    exampleTitle: 'Load the example setup?',
    exampleBody:
      'This fills the setup with an example clinic (departments, agents, a form and knowledge) so you can see how it works. It replaces your changes that are not live yet. Nothing goes live until you make changes live.',
    exampleConfirm: 'Load example',
    exampleLoaded: 'Example loaded. Look around, then make changes live when ready.',
    exampleFailed: 'Could not load the example. Try again.',
    fallback: 'The newest setup could not be loaded, so an earlier one is answering calls.',
    reloadPending: 'Your changes went live but this server has not picked them up yet. It retries on the next call.',
    drift: 'The built-in example differs from what is live now.',
  },
  home: {
    error: 'Could not load the overview.',
    callsToday: 'Calls today',
    formsWaiting: 'Forms waiting for approval',
    openQueue: 'Open the approval queue',
    openCalls: 'Open calls',
    live: (agent: string) => `Your line is live. New calls are answered by ${agent}.`,
    notLive: 'Your line is not taking calls yet. Follow the steps below.',
    liveBadge: 'Live',
    offBadge: 'Not taking calls',
    checklist: 'Set up your line',
    checklistHint: 'Work through these in order. Each step links to the page where you do it.',
    done: 'Done',
    todo: 'Not done',
    optional: 'Optional',
    steps: [
      { key: 'basics', title: 'Clinic basics & knowledge', body: 'Opening hours, services, referrals and standard sentences.', to: '/admin/knowledge', optional: false },
      { key: 'departments', title: 'Departments', body: 'Where callers can be sent.', to: '/admin/departments', optional: false },
      { key: 'forms', title: 'Forms', body: 'Questions an assistant can ask and save for staff.', to: '/admin/forms', optional: true },
      { key: 'specialists', title: 'Specialist assistants', body: 'For example an intake assistant that fills your form.', to: '/admin/agents', optional: false },
      { key: 'front_desk', title: 'Front-desk assistant', body: 'Answers first and sends callers to departments and specialists.', to: '/admin/agents', optional: false },
      { key: 'answering', title: 'Choose who answers calls', body: 'On the Agents page, pick the assistant that answers first.', to: '/admin/agents', optional: false },
      { key: 'live', title: 'Make changes live', body: 'Use "Make changes live" at the top of any setup page.', to: '/admin/versions', optional: false },
      { key: 'test_call', title: 'Place a test call', body: 'Call your line from this browser.', to: '/call', optional: false },
    ],
    exampleHint: 'New here? Load an example clinic to see how everything fits together.',
  },
  agents: {
    newAgent: 'New agent',
    entryLabel: 'Answers calls first',
    entryNone: 'Nobody yet',
    entrySave: 'Save',
    name: 'Name',
    takesCallsFor: 'Takes calls for',
    tools: 'Tools',
    voice: 'Voice',
    status: 'Status',
    active: 'Active',
    archived: 'Archived',
    entry: 'Answers calls',
    empty: 'No assistants yet.',
    emptyBody: 'Create your first assistant.',
    createFirst: 'Create your first agent',
    error: 'Could not load the agents.',
    notFound: 'There is no assistant with this name.',
    nameField: 'Name (lowercase letters, digits, _)',
    nameHint: 'A short id used on the Departments page and in reports. Cannot change later.',
    title: 'Title',
    titleHint: 'How the agent is named, e.g. "Residential Programs".',
    persona: 'Persona',
    personaHint: 'Who this agent is, its tone, and what it helps with, in plain language.',
    knowledge: 'What it knows',
    knowledgeHint: 'Short facts or FAQ answers. Shared knowledge (services, referrals, hours) is always included.',
    topic: 'Topic',
    text: 'Answer',
    addItem: 'Add a fact',
    removeItem: 'Remove fact',
    toolsHint: 'Each tool is code; pick what this agent may do. Safety checks always apply.',
    formGroup: 'Fill a form: save details, confirm the callback number, submit',
    formPick: 'Form',
    noForm: 'Choose a form',
    noForms: 'No forms yet.',
    createForm: 'Create one',
    redirectTargets: 'Where can this agent send callers? — Departments and agents',
    redirectHint: 'Departments: the caller hears that department\'s line. Agents: the caller is passed to that assistant.',
    noTargets: 'No departments or agents to send callers to yet.',
    addDepartment: 'Add a department',
    agentTarget: (name: string) => `agent: ${name}`,
    departmentTarget: 'department',
    handoff: 'When another agent passes a caller here',
    bridgeSay: 'Line the previous agent says (English)',
    bridgeSayEs: 'Line the previous agent says (Spanish)',
    greeting: 'How this agent takes over',
    greetingHint: 'A plain instruction, e.g. "Greet the caller and ask your first question."',
    archivedLabel: 'Archived (kept in history; takes no calls)',
    compiled: 'Advanced: what the assistant is told',
    compiledHint: 'Written automatically from the settings above. Shown for checking only.',
    compiledError: 'Fix the problems listed first; then this can be shown.',
    gptLive: 'Standard voice',
    luna: 'Helper rules',
    realtime: 'Single voice',
    problems: 'Problems with this assistant',
    sameEditor: 'Every setting here can be changed later.',
  },
  forms: {
    newForm: 'New form',
    empty: 'No forms yet.',
    emptyBody: 'Forms are optional. Build one if an assistant should collect details for staff to approve.',
    build: 'Build a form',
    error: 'Could not load the forms.',
    notFound: 'There is no form with this name.',
    usedBy: 'Used by',
    fieldsCount: 'Fields',
    name: 'Name (lowercase letters, digits, _)',
    title: 'Title',
    fields: 'Fields',
    fieldsHint: 'Asked in this order. The callback number and permission are always added by the system.',
    addField: 'Add a field',
    key: 'Key (lowercase letters, digits, _)',
    label: 'Label',
    type: 'Type',
    required: 'Required',
    help: 'What to ask (one line for the agent)',
    readback: 'Read-back label',
    values: 'Choices',
    stopValues: 'Stop choices: picking one hands the call to staff',
    maxLength: 'Max length',
    maxItems: 'Max items',
    minimum: 'Minimum',
    maximum: 'Maximum',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove field',
    neverCollect: 'Never collected (built-in, always refused)',
    problems: 'Problems with this form',
    archivedLabel: 'Archived (kept in history; no agent can use it)',
  },
  versions: {
    empty: 'Nothing has gone live yet.',
    error: 'Could not load the history.',
    seq: 'Number',
    label: 'Reference',
    source: 'What happened',
    by: 'By',
    when: 'When',
    note: 'Note',
    live: 'Live now',
    sources: { seed: 'Starting setup', admin: 'Changes made live', rollback: 'Went back' } as Record<string, string>,
    diffTitle: 'Changes from the version before',
    noDiff: 'No differences.',
    rollback: 'Go back to this…',
    rollbackTitle: 'Go back to this setup?',
    rollbackBody: 'A copy of this setup goes live for new calls. Nothing is deleted.',
    rollbackConfirm: 'Go back',
    rolledBack: (label: string) => `${label} is live for new calls.`,
    rollbackFailed: 'This setup does not pass today’s checks and cannot be restored.',
    notFound: 'There is no such entry.',
  },
} as const

export type AdminPageKey = keyof typeof adminCopy.pages

type Tone = 'ok' | 'error' | 'warning'

/** "human_needed" → "Human needed"; null → dash. */
export function label(value: string | null | undefined): string {
  if (!value) return adminCopy.dash
  const text = value.replace(/_/g, ' ')
  return text.charAt(0).toUpperCase() + text.slice(1)
}

export function orDash(value: string | null | undefined): string {
  return value ? value : adminCopy.dash
}

/** Local date and time for a server timestamp. */
export function formatTime(iso: string | null | undefined): string {
  if (!iso) return adminCopy.dash
  return new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })
}

/** Local HH:MM for an epoch-ms value. */
export function formatClock(ms: number): string {
  return new Date(ms).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
}

/** YYYY-MM-DD in local time. */
export function localDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

export function outcomeTone(outcome: string | null | undefined): Tone {
  if (outcome === 'crisis' || outcome === 'error') return 'error'
  if (outcome === 'routed' || outcome === 'referred' || outcome === 'clinic_form') return 'ok'
  return 'warning'
}

export function formStatusTone(status: string | null | undefined): Tone {
  if (status === 'rejected') return 'error'
  if (status === 'incomplete' || status === 'flagged') return 'warning'
  return 'ok'
}

/** Local time of day with seconds, for timeline entries. */
export function formatTimeOfDay(iso: string): string {
  return new Date(iso).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', second: '2-digit' })
}

export function yesNo(value: boolean | null | undefined): string {
  if (value === null || value === undefined) return adminCopy.dash
  return value ? 'Yes' : 'No'
}
